# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a10b873ba1bed5bb1c29269cccc691c0ec880a08cfb87a102c5f9d21503901f1a420d24e4d48e08a01f7f190c93a7a1a122f077c21da5dd13b184acb858aaa3f
  s3_bucket: 'ainame-dlib-sidekiq-demo'
test:
  secret_key_base: 1690e323094f53fe73079abb2dac397e5d90661465b7627ae0e954a97166b7481d752bb46a7aeaad9059d1065aa67489bbcbc628e18a454d1bb8a58c3fce0640
  s3_bucket: 'ainame-dlib-sidekiq-demo'

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
